#ifndef __IMPLEMENT_H
#define __IMPLEMENT_H

#include "service.h"

/* Implementation Macros */
#ifdef DEF_SERVICES
#undef DEF_SERVICES
#endif
#define DEF_SERVICES() \
	SERVICE_DEF_AI() \
	SERVICE_DEF_PHYSICS() \
	SERVICE_DEF_ANIMTEXTURE() \
	SERVICE_DEF_PROPERTY() \
	SERVICE_DEF_DEBUG() \
	SERVICE_DEF_OBJECT() \
	SERVICE_DEF_LINK() \
	SERVICE_DEF_LINKTOOLS() \
	SERVICE_DEF_SOUND() \
	SERVICE_DEF_ACTREACT() \
	SERVICE_DEF_DOOR() \
	SERVICE_DEF_LOCKED() \
	SERVICE_DEF_PUPPET() \
	SERVICE_DEF_DAMAGE() \
	SERVICE_DEF_KEY() \
	SERVICE_DEF_CAMERA() \
	SERVICE_DEF_QUEST() \
	SERVICE_DEF_LIGHT() \
	SERVICE_DEF_CONTAINER() \
	SERVICE_DEF_DATA() \
	SERVICE_DEF_PGROUP() \
	SERVICE_DEF_NETWORKING() \
	SERVICE_DEF_CD() \
	SERVICE_DEF_VERSION() \
	SERVICE_DEF_ENGINE() \
	SERVICE_DEF_WEAPON() \
	SERVICE_DEF_PICKLOCK() \
	SERVICE_DEF_BOW() \
	SERVICE_DEF_DRKINV() \
	SERVICE_DEF_DRKPOWERUPS() \
	SERVICE_DEF_PLAYERLIMBS() \
	SERVICE_DEF_DARKUI() \
	SERVICE_DEF_DARKGAME() \
	SERVICE_DEF_DARKOVERLAY() \
	SERVICE_DEF_SHOCKGAME() \
	SERVICE_DEF_SHOCKPSI() \
	SERVICE_DEF_SHOCKOBJ() \
	SERVICE_DEF_SHOCKWEAPON() \
	SERVICE_DEF_SHOCKAI() \
	SERVICE_DEF_SHOCKOVERLAY()
#ifdef EXT_SERVICES
#undef EXT_SERVICES
#endif
#define EXT_SERVICES() \
	SERVICE_EXT_AI() \
	SERVICE_EXT_PHYSICS() \
	SERVICE_EXT_ANIMTEXTURE() \
	SERVICE_EXT_PROPERTY() \
	SERVICE_EXT_DEBUG() \
	SERVICE_EXT_OBJECT() \
	SERVICE_EXT_LINK() \
	SERVICE_EXT_LINKTOOLS() \
	SERVICE_EXT_SOUND() \
	SERVICE_EXT_ACTREACT() \
	SERVICE_EXT_DOOR() \
	SERVICE_EXT_LOCKED() \
	SERVICE_EXT_PUPPET() \
	SERVICE_EXT_DAMAGE() \
	SERVICE_EXT_KEY() \
	SERVICE_EXT_CAMERA() \
	SERVICE_EXT_QUEST() \
	SERVICE_EXT_LIGHT() \
	SERVICE_EXT_CONTAINER() \
	SERVICE_EXT_DATA() \
	SERVICE_EXT_PGROUP() \
	SERVICE_EXT_NETWORKING() \
	SERVICE_EXT_CD() \
	SERVICE_EXT_VERSION() \
	SERVICE_EXT_ENGINE() \
	SERVICE_EXT_WEAPON() \
	SERVICE_EXT_PICKLOCK() \
	SERVICE_EXT_BOW() \
	SERVICE_EXT_DRKINV() \
	SERVICE_EXT_DRKPOWERUPS() \
	SERVICE_EXT_PLAYERLIMBS() \
	SERVICE_EXT_DARKUI() \
	SERVICE_EXT_DARKGAME() \
	SERVICE_EXT_DARKOVERLAY() \
	SERVICE_EXT_SHOCKGAME() \
	SERVICE_EXT_SHOCKPSI() \
	SERVICE_EXT_SHOCKOBJ() \
	SERVICE_EXT_SHOCKWEAPON() \
	SERVICE_EXT_SHOCKAI() \
	SERVICE_EXT_SHOCKOVERLAY()
#ifdef INIT_SERVICES
#undef INIT_SERVICES
#endif
#define INIT_SERVICES(_m) \
	SERVICE_IMPL_AI(_m) \
	SERVICE_IMPL_PHYSICS(_m) \
	SERVICE_IMPL_ANIMTEXTURE(_m) \
	SERVICE_IMPL_PROPERTY(_m) \
	SERVICE_IMPL_DEBUG(_m) \
	SERVICE_IMPL_OBJECT(_m) \
	SERVICE_IMPL_LINK(_m) \
	SERVICE_IMPL_LINKTOOLS(_m) \
	SERVICE_IMPL_SOUND(_m) \
	SERVICE_IMPL_ACTREACT(_m) \
	SERVICE_IMPL_DOOR(_m) \
	SERVICE_IMPL_LOCKED(_m) \
	SERVICE_IMPL_PUPPET(_m) \
	SERVICE_IMPL_DAMAGE(_m) \
	SERVICE_IMPL_KEY(_m) \
	SERVICE_IMPL_CAMERA(_m) \
	SERVICE_IMPL_QUEST(_m) \
	SERVICE_IMPL_LIGHT(_m) \
	SERVICE_IMPL_CONTAINER(_m) \
	SERVICE_IMPL_DATA(_m) \
	SERVICE_IMPL_PGROUP(_m) \
	SERVICE_IMPL_NETWORKING(_m) \
	SERVICE_IMPL_CD(_m) \
	SERVICE_IMPL_VERSION(_m) \
	SERVICE_IMPL_ENGINE(_m) \
	SERVICE_IMPL_WEAPON(_m) \
	SERVICE_IMPL_PICKLOCK(_m) \
	SERVICE_IMPL_BOW(_m) \
	SERVICE_IMPL_DRKINV(_m) \
	SERVICE_IMPL_DRKPOWERUPS(_m) \
	SERVICE_IMPL_PLAYERLIMBS(_m) \
	SERVICE_IMPL_DARKUI(_m) \
	SERVICE_IMPL_DARKGAME(_m) \
	SERVICE_IMPL_DARKOVERLAY(_m) \
	SERVICE_IMPL_SHOCKGAME(_m) \
	SERVICE_IMPL_SHOCKPSI(_m) \
	SERVICE_IMPL_SHOCKOBJ(_m) \
	SERVICE_IMPL_SHOCKWEAPON(_m) \
	SERVICE_IMPL_SHOCKAI(_m) \
	SERVICE_IMPL_SHOCKOVERLAY(_m)

#endif
